on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install Rust[Stable + Wasm]
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Install Rust[Nightly]
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - uses: Swatinem/rust-cache@v2

      - name: Install trunk
        run: cargo install trunk

      - name: Install Fluent Web Cli
        run: cargo +nightly install fluent_web

      - name: Build project
        run: trunk build --release
